name: News tweet bot
on:
  schedule:
    - cron: "*/10 * * * *" # Run every 10 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  check_and_tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download history file if exists
        uses: actions/download-artifact@v3
        with:
          name: tweet-history
          path: ./
        continue-on-error: true

      - name: Run news tweet bot (single check)
        run: python news_tweet_bot.py --single-check
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Upload updated history file
        uses: actions/upload-artifact@v3
        with:
          name: tweet-history
          path: tweet_history.json
          retention-days: 1
